---
dependencies: []

galaxy_info:
  role_name: dotfiles
  author: njhoffman
  description: Docker for Linux.
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.5
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - stretch
        - buster
        - bullseye
    - name: Ubuntu
      versions:
        - focal
        - groovy
        - hirsute
