---
roles:
  # - role: viasite-ansible.zsh
  - name: manala.zsh
  # - name: manala.ohmyzsh

  # # from galaxy
  # - name: yatesr.timezone
  #
  # # from locally cloned git repository (git+file:// requires full paths)
  # - src: git+file:///home/bennojoy/nginx
  #
  # # from GitHub
  # - src: https://github.com/bennojoy/nginx
  #
  # # from GitHub, overriding the name and specifying a specific tag
  # - name: nginx_role
  #   src: https://github.com/bennojoy/nginx
  #   version: master
  #
  # # from GitHub, specifying a specific commit hash
  # - src: https://github.com/bennojoy/nginx
  #   version: "ee8aa41"
  #
  # # from a webserver, where the role is packaged in a tar.gz
  # - name: http-role-gz
  #   src: https://some.webserver.example.com/files/master.tar.gz
  #
  # # from a webserver, where the role is packaged in a tar.bz2
  # - name: http-role-bz2
  #   src: https://some.webserver.example.com/files/master.tar.bz2
  #
  # # from a webserver, where the role is packaged in a tar.xz (Python 3.x only)
  # - name: http-role-xz
  #   src: https://some.webserver.example.com/files/master.tar.xz
  #
  # # from Bitbucket
  # - src: git+https://bitbucket.org/willthames/git-ansible-galaxy
  #   version: v1.4
  #
  # # from Bitbucket, alternative syntax and caveats
  # - src: https://bitbucket.org/willthames/hg-ansible-galaxy
  #   scm: hg
  #
  # # from GitLab or other git-based scm, using git+ssh
  # - src: git@gitlab.company.com:mygroup/ansible-base.git
  #   scm: git
  #   version: "0.1"  # quoted, so YAML doesn't parse this as a floating-point value
