----
name: Transfer ssh key and verify github connection
hosts: all
tasks:
  - name: Ensure GitHub deploy key is present on the server.
    copy:
      content: "{{ deploy_private_key }}"
      dest: /var/www/.ssh/deploy_key
      mode: 0600
      owner: www-data
      group: www-data
  - name: Clone the code repository to the docroot.
    git:
      repo: ssh://"{{ provision_repo_src }}"
      dest: "{{ provision_repo_dest }}"
      accept_hostkey: yes
      key_file: "{{ deploy_local_user_home }}/.ssh/ansible_deploy"

