#!/bin/bash

# remove old host keys
ssh-keygen -f "$HOME/.ssh/known_hosts" -R "[localhost]:5000"

sshpass -p screencast ssh \
  -vvv \
  -p 5000 \
  -o UserKnownHostsFile=/dev/null \
  -o StrictHostKeyChecking=no \
  root@localhost

