---
# - name: add conky apt repository
#   become: true
#   shell: add-apt-repository ppa:mark-pcnetspec/conky-manager-pm9

- name: add conky and related utilities
  become: true
  package:
    name:
      - conky-all
      - lm-sensors
      - hddtemp
      - cmake
      - libimlib2-dev
      - libncurses5-dev
      - libx11-dev
      - libxdamage-dev
      - libxft-dev
      - libxinerama-dev
      - libxml2-dev
      - libxext-dev
      - libcurl4-openssl-dev
      - liblua5.3-dev
      - ncal
      - xdotool

# run sudo sensors-detect to add appropriate sensor modules to the kernel
