---
# install pure shell as shell option
# https://github.com/sindresorhus/pure
- import_tasks: ./fonts.yml
  tags: [ fonts ]

- import_tasks: ./terminal.yml
  tags: [ terminal ]

- import_tasks: ./tmux.yml
  tags: [ tmux ]

- import_tasks: ./zsh.yml
  tags: [ zsh ]


- name: install misc shell packages
  become: true
  package:
    name:
     - ansiweather
     - pass
     - gnupg2 # for pass
     - libtokyocabinet-dev # for neomutt
     # https://github.com/neomutt/neomutt.git
     - neomutt # ./configure --gnutls --gpgme --gss --sasl --tokyocabinet
     - ssed
     - gawk # mawk is NOT awk, gawk is
     - tty-clock
     - zenity

- import_tasks: ../../essentials/tasks/python.yml
- name: install misc shell packages from python
  shell: pip3 install "{{ item }}"
  with_items:
    - powerline-status

- import_tasks: ../../essentials/tasks/ruby.yml
- name: install misc shell gems from ruby
  shell: gem install "{{ item }}"
  with_items:
    - colorls

- name: create symbolic links to config directory
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - { src: "{{ resources_dir }}/config/.shell", dest: "~/.shell" }

- name: copy .zshrc files to home directory
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - { src: "{{ resources_dir }}/config/.shell/.zshrc.root", dest: "~/.zshrc" }
    - { src: "{{ resources_dir }}/config/.shell/.zshrc.local", dest: "~/.zshrc.local" }

# TODO: at some point ~/.config/gtk-** gets cleared, need to recopy from ~/resources
- name: set gnome preferences
  shell: gsettings set {{ item.path }} {{ item.name }} {{ item.value }}
  with_items:
    - { path: "org.gnome.desktop.interface", name: "gtk-theme", value: "Juno-ocean" }
    - { path: "org.gnome.desktop.wm.preferences", name: "theme", value: "Juno-ocean" }
    - { path: "org.gnome.desktop.interface", name: "cursor-theme", value: "Yaru" }
    - { path: "org.gnome.desktop.interface", name: "icon-theme", value: "Yaru" }
    - { path: "org.gnome.desktop.interface", name: "cursor-blink-time", value: "800" }
    - { path: "org.gnome.desktop.interface", name: "cursor-blink-timeout", value: "604800000" }

  # themes: Juno-ocean, Nordic-darker, Sweet-mars
  # cursors: DMZ-Black, DMZ-White, Yaru, Handhelds, Redglass, Whiteglass
  # sound: Default, Yaru
  # icons:
  #   Adwaita, DMZ-Black, DMZ-White, HiColor, HighContrast, Humanity, Humanity-Dark,
  #   LoginIcons, Ubuntu-mono-light, Ubuntu-mono-dark, Yaru

# git clone https://github.com/dylanaraps/pywal
# cd pywal && pip3 install --user .

# https://github.com/vineetred/flowy

# ln -s ~/.shell/completions ~/.oh-my-zsh/completions

# alacritty: add-apt-repository ppa:mmstick76/alacritty && apt-get ionstall alacritty
# apt-get install cmake pkg-config libfreetype6-dev libfontconfig1-dev libxcb-xfixes0-dev python3
# git clone https://github.com/alacritty/alacritty.git && cd alacritty
# rustup override set stable
# rustup update stable
# cargo build --release
# sudo cp target/release/alacritty /usr/local/bin # or anywhere else in $PATH
# sudo cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg
# sudo desktop-file-install extra/linux/Alacritty.desktop
# sudo update-desktop-database
# # cargo install --git https://github.com/alacritty/alacritty.git
# # manual page
# sudo mkdir -p /usr/local/share/man/man1
# gzip -c extra/alacritty.man | sudo tee /usr/local/share/man/man1/alacritty.1.gz > /dev/null
# # zsh shell completions
# mkdir -p ${ZDOTDIR:-~}/.zsh_functions
# echo 'fpath+=${ZDOTDIR:-~}/.zsh_functions' >> ${ZDOTDIR:-~}/.zshrc
# cp extra/completions/_alacritty ${ZDOTDIR:-~}/.zsh_functions/_alacritty
# # bash shell completions
# echo "source $(pwd)/extra/completions/alacritty.bash" >> ~/.bashrc
