---
- name: install python3 and pip
  become: true
  package:
    name:
      - python3
      - python3-dev
      - python3-pip
      - python-is-python3
    state: present
    
- name: update python package manager (pip)
  shell: "{{ item }}"
  with_items:
    - pip3 install --upgrade pip
